//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_setQuiz
    {
        public int QuizId { get; set; }
        public Nullable<System.DateTime> Quiz_date { get; set; }
        public Nullable<int> Quiz_fk_std { get; set; }
        public string Quiz_name { get; set; }
        public Nullable<int> std_score { get; set; }
    
        public virtual student student { get; set; }
    }
}
